spring:
  application:
    name: image-server

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB

  mvc:
    contentnegotiation:
      favor-parameter: true
      favor-path-extension: true

logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN

server:
  port: 8080

#server:
#  port: 443
#  ssl:
#    key-store: /root/keystore.p12
#    key-store-password: password?
#    key-password: ?
#    key-alias: tomcat
#    key-store-type: PKCS12
#    trust-store: /root/image-server.ts
#    trust-store-password: password?